name: skool
description: "A new Flutter project."
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.3.4 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  easy_localization: ^3.0.2
  auto_route: ^7.8.3

  #UI
  flutter_svg: ^2.0.10+1
  dropdown_button2: ^2.3.8

  #loading
  shimmer: ^2.0.0

  #NERWORK
  dio: ^5.3.2
  retrofit: ^4.0.1
  pretty_dio_logger: ^1.3.1
  json_serializable: ^6.7.1
  json_annotation: ^4.8.1
  build_runner: ^2.1.5

  # STATE MANAGEMENT
  flutter_bloc: ^8.1.3
  equatable: ^2.0.5
  provider: ^6.0.5
  get_it: ^7.6.0

  #DB
  shared_preferences: ^2.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/svg/
    - assets/svg/icon/
    - assets/svg/home/
    - assets/svg/lang/
    - assets/svg/modal/
    - assets/svg/bnavigation/
    - assets/image/
